name: Yarn Linting & Typescript Checking
on: [pull_request]
jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'yarn'
            - run: yarn install
            - run: yarn lint
              env:
                  NODE_ENV: development
            - run: yarn ts
